# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mammoth School SQL Intro
email: jpetty@harrys.com
description: > # this means to ignore newlines until "baseurl:"
  Let's learn some SQL
baseurl: "/mammoth-school-sql-intro" # the subpath of your site, e.g. /blog
url: "https://pettyjamesm.github.io/" # the base hostname & protocol for your site
permalink: '/guides/:slug.html'

# Build settings
markdown: kramdown
